"""Add notify on User table

Revision ID: 45937c7dc524
Revises: b433643d4dfa
Create Date: 2024-01-11 15:39:56.772071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45937c7dc524'
down_revision: Union[str, None] = 'b433643d4dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify')
    # ### end Alembic commands ###
